### ISSUE TITLE
Implement a generator bridge for the STM32CubeMX Generator

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/generator-bridge#7]
**Describe The Problem To Be Solved**
For using the [STM32CubeMX](https://www.st.com/content/st_com/en/stm32cubemx.html) tool as generator with the CMSIS-Toolbox Simplified Generator Workflow CLI application is required to `bridge` between these two domains and allow STM32CubeMX to contribute Source Code to projects which are configured and build using the CMSIS-Toolbox.

[Proposal](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/Simplified%20Generator%20Proposal.md)

**(Optional): Suggest A Solution**
- Create a CLI application using GOlang and produce binaries for all supported host platforms CMSIS-Toolbox supports
- The application is invoked by `csolution run ...` command
- The application reads *.cbuild-gen-idx.yml file passed as argument
- The application constructs the command line for invoking STM32CubeMX
- The application launches the STM32CubeMX generator and waits for it to generate code (code generation is triggered by user) and return (return code != 0 => error)
- The application reads output description from the STM32CubeMX and converts meta information in *.cgen.yml file(s)
- The application terminates

* Caveats and considerations for the future
- At this point it is required for STM32CubeMX to be terminated by the user after the generation is completed
- The application may launch STM32CubeMX without waiting but instead waiting for an output file being generated by STM32CubeMX
- The application shall check that it does not launch a new instance of STM32CubeMX for the same *.ioc project if one is already running.
- It maybe required the STM32CubeMX is re-reading input information.

**Comment by thorstendb-ARM** [comment]
Released 0.9.0 as initial version.
